version: '4.4'

services:
    app:
        image: node
        volumes: 
            - ./:/app:cached
        working_dir: /app
        ports:
          - 3000:3000
        command: npm start
        tty: true



